model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 64
  loss_type: 'H'
  gamma: 10.0
  betta: 0.5
  max_capacity: 100
  Capacity_max_iter: 100000
  model: resnet18

exp_params:
  dataset: allData
  data_path: "/media/mmm/DATADRIVE2/full_dataset/train"
#  data_path: "/home/mmm/Desktop/Dor/Gavia_Adom/datasets/spectrograms_3C_png"
  df_path: "/"
  auto_crop: False
  img_size: [128,128] # should be squares of 2 (until 128)
  batch_size: 128 # Better to have a square
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.9

trainer_params:
  gpus: 1
#  max_nb_epochs: 50
  max_epochs: 2

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_B-1"
  manual_seed: 1265

#model_params:
#  name: 'BetaVAE'
#  in_channels: 3
#  latent_dim: 128
#  loss_type: 'B'
#  gamma: 10.0
#  max_capacity: 25
#  Capacity_max_iter: 10000

#exp_params:
 # dataset: celeba
  #data_path: "../../shared/Data/"
  #img_size: 64
  #batch_size: 144 # Better to have a square number
  #LR: 0.0005
  #weight_decay: 0.0
  #scheduler_gamma: 0.95

#trainer_params:
 # gpus: 1
  #max_nb_epochs: 50
  #max_epochs: 50

#logging_params:
 # save_dir: "logs/"
#  name: "BetaVAE_B"
#  manual_seed: 1265
#